"""Kuvira Sports demo seed data — pickleball-first, Bangalore/Mumbai."""
from datetime import datetime, timezone, timedelta
import uuid

def _id(): return str(uuid.uuid4())

NOW = datetime.now(timezone.utc)

SPORTS = [
    {"id": "sport-pickleball", "name": "Pickleball", "slug": "pickleball", "icon": "tennisball-outline", "active": True, "order": 1},
    {"id": "sport-badminton", "name": "Badminton", "slug": "badminton", "icon": "tennisball-outline", "active": True, "order": 2},
    {"id": "sport-tennis", "name": "Tennis", "slug": "tennis", "icon": "tennisball-outline", "active": True, "order": 3},
    {"id": "sport-tabletennis", "name": "Table Tennis", "slug": "table-tennis", "icon": "tennisball-outline", "active": True, "order": 4},
    {"id": "sport-basketball", "name": "Basketball", "slug": "basketball", "icon": "basketball-outline", "active": True, "order": 5},
]

SKILL_LEVELS = ["Beginner", "Intermediate", "Advanced", "Pro"]

FACILITIES = [
    {
        "id": "fac-koramangala",
        "name": "Kuvira Koramangala Arena",
        "city": "Bangalore",
        "area": "Koramangala",
        "address": "80 Feet Rd, 4th Block, Koramangala",
        "lat": 12.9352, "lng": 77.6245,
        "sports": ["sport-pickleball", "sport-badminton"],
        "amenities": ["Parking", "Locker Room", "Cafe", "Pro Shop", "AC", "Coaching"],
        "rating": 4.8, "reviews_count": 214,
        "price_per_hour": 800,
        "image": "https://images.unsplash.com/photo-1618551763300-dc7eb8ce3560?w=1200&q=80",
        "images": [
            "https://images.unsplash.com/photo-1618551763300-dc7eb8ce3560?w=1200&q=80",
            "https://images.unsplash.com/photo-1737476997205-b3336182f215?w=1200&q=80",
        ],
        "courts_count": 6, "is_experience_center": True,
        "description": "Kuvira's flagship experience center. Championship courts, AI camera analytics, on-site coaching.",
    },
    {
        "id": "fac-indiranagar",
        "name": "Smash Point Indiranagar",
        "city": "Bangalore",
        "area": "Indiranagar",
        "address": "100 Feet Rd, Indiranagar",
        "lat": 12.9784, "lng": 77.6408,
        "sports": ["sport-pickleball", "sport-tennis"],
        "amenities": ["Parking", "Cafe", "Locker Room"],
        "rating": 4.6, "reviews_count": 158,
        "price_per_hour": 650,
        "image": "https://images.unsplash.com/photo-1622279488937-3f2eff28f9c3?w=1200&q=80",
        "images": ["https://images.unsplash.com/photo-1622279488937-3f2eff28f9c3?w=1200&q=80"],
        "courts_count": 4, "is_experience_center": False,
        "description": "Premium outdoor pickleball courts in the heart of Indiranagar.",
    },
    {
        "id": "fac-hsr",
        "name": "HSR Sports Hub",
        "city": "Bangalore",
        "area": "HSR Layout",
        "address": "Sector 2, HSR Layout",
        "lat": 12.9116, "lng": 77.6474,
        "sports": ["sport-pickleball", "sport-badminton", "sport-tabletennis"],
        "amenities": ["Parking", "AC", "Cafe"],
        "rating": 4.5, "reviews_count": 92,
        "price_per_hour": 550,
        "image": "https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=1200&q=80",
        "images": ["https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=1200&q=80"],
        "courts_count": 3, "is_experience_center": False,
        "description": "Neighborhood favorite with multiple courts and friendly community.",
    },
    {
        "id": "fac-bandra",
        "name": "Kuvira Bandra Experience Center",
        "city": "Mumbai",
        "area": "Bandra West",
        "address": "Linking Road, Bandra West",
        "lat": 19.0596, "lng": 72.8295,
        "sports": ["sport-pickleball", "sport-tennis"],
        "amenities": ["Parking", "Locker Room", "Cafe", "Pro Shop", "AC", "AI Cameras"],
        "rating": 4.9, "reviews_count": 341,
        "price_per_hour": 1200,
        "image": "https://images.unsplash.com/photo-1544736150-6b5b7f3e3d3f?w=1200&q=80",
        "images": ["https://images.unsplash.com/photo-1544736150-6b5b7f3e3d3f?w=1200&q=80"],
        "courts_count": 8, "is_experience_center": True,
        "description": "The future of sports — 8 courts, AI cameras, coaching, community.",
    },
]

PLAYERS = [
    {"id": "player-arjun", "name": "Arjun Mehta", "avatar": "https://i.pravatar.cc/300?img=12",
     "city": "Bangalore", "area": "Koramangala", "primary_sport": "sport-pickleball",
     "skill_level": "Intermediate", "rating": 4.2, "matches_played": 47, "wins": 29,
     "playing_style": "Aggressive baseliner", "availability": "Evenings & weekends",
     "bio": "3x/week pickleball. Love a good rally."},
    {"id": "player-priya", "name": "Priya Sharma", "avatar": "https://i.pravatar.cc/300?img=45",
     "city": "Bangalore", "area": "Indiranagar", "primary_sport": "sport-pickleball",
     "skill_level": "Advanced", "rating": 4.6, "matches_played": 82, "wins": 61,
     "playing_style": "Net dominator", "availability": "Weekday mornings",
     "bio": "Former state tennis player, now hooked on pickleball."},
    {"id": "player-rohan", "name": "Rohan Kapoor", "avatar": "https://i.pravatar.cc/300?img=13",
     "city": "Bangalore", "area": "HSR Layout", "primary_sport": "sport-pickleball",
     "skill_level": "Intermediate", "rating": 4.0, "matches_played": 31, "wins": 18,
     "playing_style": "All-court player", "availability": "Weekends",
     "bio": "Weekend warrior looking for consistent doubles partners."},
    {"id": "player-sara", "name": "Sara D'Souza", "avatar": "https://i.pravatar.cc/300?img=47",
     "city": "Mumbai", "area": "Bandra", "primary_sport": "sport-pickleball",
     "skill_level": "Pro", "rating": 4.9, "matches_played": 156, "wins": 132,
     "playing_style": "Precision & finesse", "availability": "Flexible",
     "bio": "Pro-level pickleball coach. Tournament veteran."},
    {"id": "player-kabir", "name": "Kabir Singh", "avatar": "https://i.pravatar.cc/300?img=15",
     "city": "Bangalore", "area": "Koramangala", "primary_sport": "sport-pickleball",
     "skill_level": "Beginner", "rating": 3.2, "matches_played": 8, "wins": 3,
     "playing_style": "Learning", "availability": "Weekday evenings",
     "bio": "Just started, looking to improve fast."},
    {"id": "player-anaya", "name": "Anaya Iyer", "avatar": "https://i.pravatar.cc/300?img=48",
     "city": "Bangalore", "area": "Indiranagar", "primary_sport": "sport-pickleball",
     "skill_level": "Advanced", "rating": 4.5, "matches_played": 71, "wins": 52,
     "playing_style": "Aggressive net play", "availability": "Evenings",
     "bio": "Tournament competitor. Always up for a challenge."},
]

COACHES = [
    {"id": "coach-vikram", "name": "Vikram Rao", "avatar": "https://i.pravatar.cc/300?img=52",
     "sports": ["sport-pickleball"], "city": "Bangalore",
     "certifications": ["IPTPA Level 2", "PPR Certified"],
     "experience_years": 8, "rating": 4.9, "reviews_count": 87,
     "price_per_session": 1500, "specialties": ["Serve technique", "Net play", "Strategy"],
     "bio": "Former national tennis player, now Bangalore's most-booked pickleball coach.",
     "image": "https://images.unsplash.com/photo-1544736150-6b5b7f3e3d3f?w=800&q=80"},
    {"id": "coach-neha", "name": "Neha Malhotra", "avatar": "https://i.pravatar.cc/300?img=44",
     "sports": ["sport-pickleball", "sport-tennis"], "city": "Mumbai",
     "certifications": ["IPTPA Level 3", "USPTA"],
     "experience_years": 12, "rating": 5.0, "reviews_count": 143,
     "price_per_session": 2200, "specialties": ["Tournament prep", "Mental game", "Doubles strategy"],
     "bio": "Elite coach, produced 4 national medalists.",
     "image": "https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=800&q=80"},
]

EVENTS = [
    {"id": "event-monsoon-mixer", "name": "Monsoon Pickleball Mixer",
     "date": (NOW + timedelta(days=5)).isoformat(),
     "facility_id": "fac-koramangala", "city": "Bangalore",
     "sport": "sport-pickleball", "type": "Social Mixer",
     "price": 500, "participants_count": 32, "max_participants": 48,
     "image": "https://images.unsplash.com/photo-1737476997205-b3336182f215?w=1200&q=80",
     "description": "Casual doubles mixer with rotating partners. All levels welcome."},
    {"id": "event-womens-clinic", "name": "Women's Pickleball Clinic",
     "date": (NOW + timedelta(days=10)).isoformat(),
     "facility_id": "fac-indiranagar", "city": "Bangalore",
     "sport": "sport-pickleball", "type": "Clinic",
     "price": 800, "participants_count": 12, "max_participants": 16,
     "image": "https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=1200&q=80",
     "description": "3-hour clinic covering serves, dinks, and match play."},
]

TOURNAMENTS = [
    {"id": "trn-bangalore-open", "name": "Bangalore Pickleball Open 2026",
     "date": (NOW + timedelta(days=21)).isoformat(),
     "facility_id": "fac-koramangala", "city": "Bangalore",
     "sport": "sport-pickleball", "format": "Doubles",
     "skill_level": "Intermediate+", "entry_fee": 1500,
     "prize_pool": 100000, "participants_count": 42, "max_participants": 64,
     "image": "https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=1200&q=80",
     "description": "The biggest pickleball tournament in South India."},
    {"id": "trn-mumbai-championship", "name": "Mumbai Pickleball Championship",
     "date": (NOW + timedelta(days=35)).isoformat(),
     "facility_id": "fac-bandra", "city": "Mumbai",
     "sport": "sport-pickleball", "format": "Singles & Doubles",
     "skill_level": "All levels", "entry_fee": 2000,
     "prize_pool": 200000, "participants_count": 78, "max_participants": 128,
     "image": "https://images.unsplash.com/photo-1622279488937-3f2eff28f9c3?w=1200&q=80",
     "description": "National-level tournament with pro players."},
]

GAMES = [
    {"id": "game-1", "sport": "sport-pickleball", "facility_id": "fac-koramangala",
     "host_id": "player-arjun", "date": (NOW + timedelta(days=1, hours=2)).isoformat(),
     "duration_min": 90, "skill_level": "Intermediate", "format": "Doubles",
     "max_players": 4, "current_players": ["player-arjun", "player-rohan"],
     "price_per_person": 200, "notes": "Casual doubles, 2 spots open."},
    {"id": "game-2", "sport": "sport-pickleball", "facility_id": "fac-indiranagar",
     "host_id": "player-priya", "date": (NOW + timedelta(days=2, hours=8)).isoformat(),
     "duration_min": 60, "skill_level": "Advanced", "format": "Doubles",
     "max_players": 4, "current_players": ["player-priya", "player-anaya", "player-sara"],
     "price_per_person": 250, "notes": "Competitive doubles. Advanced only."},
    {"id": "game-3", "sport": "sport-pickleball", "facility_id": "fac-hsr",
     "host_id": "player-kabir", "date": (NOW + timedelta(days=3, hours=1)).isoformat(),
     "duration_min": 60, "skill_level": "Beginner", "format": "Doubles",
     "max_players": 4, "current_players": ["player-kabir"],
     "price_per_person": 150, "notes": "Beginner-friendly, let's learn together!"},
    {"id": "game-4", "sport": "sport-pickleball", "facility_id": "fac-koramangala",
     "host_id": "player-anaya", "date": (NOW + timedelta(days=4, hours=6)).isoformat(),
     "duration_min": 90, "skill_level": "Intermediate", "format": "Mixed Doubles",
     "max_players": 4, "current_players": ["player-anaya", "player-arjun"],
     "price_per_person": 200, "notes": "Mixed doubles, need 1M + 1F."},
]

PRODUCTS = [
    {"id": "prod-paddle-pro", "name": "Kuvira Pro Carbon Paddle",
     "category": "Paddles", "sport": "sport-pickleball", "brand": "Kuvira",
     "price": 8999, "original_price": 11999, "rating": 4.8, "reviews_count": 124,
     "image": "https://images.unsplash.com/photo-1659318006095-4d44845f3a1b?w=800&q=80",
     "images": ["https://images.unsplash.com/photo-1659318006095-4d44845f3a1b?w=800&q=80"],
     "description": "Championship-grade carbon fiber paddle. Balanced power and control.",
     "specs": {"Weight": "8.0 oz", "Material": "Carbon Fiber", "Grip": "4.25\"", "Shape": "Elongated"},
     "recommended_skill": "Intermediate+", "playing_style": "Aggressive",
     "stock": 24},
    {"id": "prod-paddle-control", "name": "Kuvira Control X Paddle",
     "category": "Paddles", "sport": "sport-pickleball", "brand": "Kuvira",
     "price": 6499, "original_price": 7999, "rating": 4.6, "reviews_count": 87,
     "image": "https://images.unsplash.com/photo-1659318006095-4d44845f3a1b?w=800&q=80",
     "images": ["https://images.unsplash.com/photo-1659318006095-4d44845f3a1b?w=800&q=80"],
     "description": "Precision-focused paddle for all-court control players.",
     "specs": {"Weight": "7.6 oz", "Material": "Fiberglass", "Grip": "4.125\"", "Shape": "Standard"},
     "recommended_skill": "Beginner+", "playing_style": "Control",
     "stock": 40},
    {"id": "prod-court-shoes", "name": "Kuvira Court Grip Shoes",
     "category": "Shoes", "sport": "sport-pickleball", "brand": "Kuvira",
     "price": 5499, "original_price": 6999, "rating": 4.7, "reviews_count": 203,
     "image": "https://images.unsplash.com/photo-1623788975845-7d3e0adbae7c?w=800&q=80",
     "images": ["https://images.unsplash.com/photo-1623788975845-7d3e0adbae7c?w=800&q=80"],
     "description": "Court-tuned lateral grip. Engineered for pickleball footwork.",
     "specs": {"Sole": "Non-marking gum rubber", "Upper": "Mesh + TPU", "Weight": "310g"},
     "recommended_skill": "All levels", "playing_style": "Any",
     "stock": 55},
    {"id": "prod-balls", "name": "Kuvira Tournament Balls (12-pack)",
     "category": "Balls", "sport": "sport-pickleball", "brand": "Kuvira",
     "price": 999, "original_price": 1299, "rating": 4.5, "reviews_count": 312,
     "image": "https://images.unsplash.com/photo-1622279488937-3f2eff28f9c3?w=800&q=80",
     "images": ["https://images.unsplash.com/photo-1622279488937-3f2eff28f9c3?w=800&q=80"],
     "description": "USAPA-approved tournament balls. Consistent bounce, long life.",
     "specs": {"Pack": "12 balls", "Type": "Outdoor", "Certification": "USAPA"},
     "recommended_skill": "All levels", "playing_style": "Any",
     "stock": 200},
    {"id": "prod-bag", "name": "Kuvira Elite Racket Bag",
     "category": "Bags", "sport": "sport-pickleball", "brand": "Kuvira",
     "price": 3499, "original_price": 4499, "rating": 4.6, "reviews_count": 76,
     "image": "https://images.unsplash.com/photo-1544736150-6b5b7f3e3d3f?w=800&q=80",
     "images": ["https://images.unsplash.com/photo-1544736150-6b5b7f3e3d3f?w=800&q=80"],
     "description": "Holds 6 paddles, shoes, apparel. Thermal shielding.",
     "specs": {"Capacity": "6 paddles", "Material": "Ballistic Nylon"},
     "recommended_skill": "All levels", "playing_style": "Any",
     "stock": 30},
    {"id": "prod-apparel", "name": "Kuvira Performance Tee",
     "category": "Apparel", "sport": "sport-pickleball", "brand": "Kuvira",
     "price": 1499, "original_price": 1999, "rating": 4.4, "reviews_count": 158,
     "image": "https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800&q=80",
     "images": ["https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800&q=80"],
     "description": "Moisture-wicking performance tee. Athletic fit.",
     "specs": {"Fabric": "Recycled polyester", "Fit": "Athletic"},
     "recommended_skill": "All levels", "playing_style": "Any",
     "stock": 100},
]

COMMUNITY_POSTS = [
    {"id": "post-1", "author_id": "player-sara",
     "content": "Just won my first tournament! Thanks to everyone at Kuvira Bandra 🏆",
     "image": "https://images.unsplash.com/photo-1622279488937-3f2eff28f9c3?w=1200&q=80",
     "likes": 47, "comments_count": 12,
     "created_at": (NOW - timedelta(hours=3)).isoformat()},
    {"id": "post-2", "author_id": "player-priya",
     "content": "Great morning session at Indiranagar. Looking for a doubles partner for Sunday's mixer!",
     "image": None, "likes": 18, "comments_count": 5,
     "created_at": (NOW - timedelta(hours=8)).isoformat()},
    {"id": "post-3", "author_id": "player-arjun",
     "content": "New paddle day! The Kuvira Pro Carbon feels incredible. Anyone else made the switch?",
     "image": "https://images.unsplash.com/photo-1659318006095-4d44845f3a1b?w=1200&q=80",
     "likes": 32, "comments_count": 8,
     "created_at": (NOW - timedelta(days=1)).isoformat()},
]
